server_name: "valhalla"
server_port: 8088
server_loglevel: "INFO"
database_file: "database.db"
server_host: "localhost"
server_password: "sekret_password"
server_access_username: "user"
jwt_secret: "sekrit"